name       : python-commonmark
version    : 0.9.1
release    : 2
source     :
    - https://github.com/readthedocs/commonmark.py/archive/0.9.1.tar.gz : b5d5be6af35a183c3f915d714b31b61e6918894051114419f9ac0bbb715bf4c6
license    : BSD-3-Clause
component  : programming.python
summary    : A Python CommonMark parser
description: |
    commonmark.py is a pure Python port of jgm's commonmark.js, a Markdown parser and renderer for the CommonMark specification, using only native modules.
build      : |
    %python3_setup
install    : |
    %python3_install
    mv $installdir/usr/bin/cmark $installdir/usr/bin/cmark-python
